# Generated by Django 4.1.1 on 2022-10-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_category_alter_recipe_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='recipes/covers/%Y/%m/%d/'),
        ),
    ]
